# site settings
title: Alfa Blockchain Consulting
subtitle: Cryptocurrency financing and ICO consulting
email: info@alfabc.io
description: 
#baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "http://alfabc.io" # the base hostname & protocol for your site
#author:
street_address: Carrer d'Aribau, 175, Principal 1 B
city: Barcelona
#state: TN
zip_code: 08036
country: Spain
phone: +34 931 12 54 23

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
#500px_url:
#facebook_url:
github_url: http://github.com/alfabc
#gitlab_url: https://gitlab.com/u/alfabc
#googleplus_url: https://plus.google.com/u/0/+alfabc
#instagram_url: https://instagram.com
#linkedin_url: https://www.linkedin.com/in/alfabc
#pinterest_url:
#slack_url:
twitter_url: https://twitter.com/alfabcn

# build settings
markdown: kramdown

sass:
  style: compressed

#theme: jekyll-theme-hacker
